const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const versionPath = path.join(root, 'version.json');

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function replaceRequired(content, pattern, replacement, label) {
  if (!pattern.test(content)) {
    throw new Error(`Could not find ${label}.`);
  }
  pattern.lastIndex = 0;
  return content.replace(pattern, replacement);
}

function validateVersionInfo(info) {
  if (!info || typeof info !== 'object') {
    throw new Error('version.json must contain an object.');
  }
  if (typeof info.version !== 'string' || !info.version.trim()) {
    throw new Error('version.json version must be a non-empty string.');
  }
  if (!Number.isInteger(info.androidVersionCode) || info.androidVersionCode <= 0) {
    throw new Error('version.json androidVersionCode must be a positive integer.');
  }
  if (typeof info.iosBuildNumber !== 'string' || !info.iosBuildNumber.trim()) {
    throw new Error('version.json iosBuildNumber must be a non-empty string.');
  }
  if (!Number.isInteger(info.hotUpdateVersionCode) || info.hotUpdateVersionCode <= 0) {
    throw new Error('version.json hotUpdateVersionCode must be a positive integer.');
  }
}

function syncPackageJson(info) {
  const packagePath = path.join(root, 'package.json');
  const pkg = readJson(packagePath);
  pkg.version = info.version;
  writeJson(packagePath, pkg);
}

function syncPackageLock(info) {
  const lockPath = path.join(root, 'package-lock.json');
  if (!fs.existsSync(lockPath)) return;

  const lock = readJson(lockPath);
  lock.version = info.version;
  if (lock.packages && lock.packages['']) {
    lock.packages[''].version = info.version;
  }
  writeJson(lockPath, lock);
}

function syncIosProject(info) {
  const versionConfigPath = path.join(root, 'ios', 'LineAI', 'Version.xcconfig');
  fs.writeFileSync(
    versionConfigPath,
    [
      '// Generated by scripts/sync-version.js from version.json. Do not edit manually.',
      `LINECODE_MARKETING_VERSION = ${info.version}`,
      `LINECODE_CURRENT_PROJECT_VERSION = ${info.iosBuildNumber}`,
      '',
    ].join('\n'),
    'utf8',
  );

  const projectPath = path.join(root, 'ios', 'LineAI.xcodeproj', 'project.pbxproj');
  if (!fs.existsSync(projectPath)) return;

  let content = fs.readFileSync(projectPath, 'utf8');
  content = replaceRequired(
    content,
    /MARKETING_VERSION = [^;]+;/g,
    'MARKETING_VERSION = "$(LINECODE_MARKETING_VERSION)";',
    'iOS MARKETING_VERSION',
  );
  content = replaceRequired(
    content,
    /CURRENT_PROJECT_VERSION = [^;]+;/g,
    'CURRENT_PROJECT_VERSION = "$(LINECODE_CURRENT_PROJECT_VERSION)";',
    'iOS CURRENT_PROJECT_VERSION',
  );
  fs.writeFileSync(projectPath, content, 'utf8');
}

function main() {
  const info = readJson(versionPath);
  validateVersionInfo(info);
  syncPackageJson(info);
  syncPackageLock(info);
  syncIosProject(info);
  console.log(
    `Version synced: ${info.version} ` +
      `(android ${info.androidVersionCode}, ios ${info.iosBuildNumber}, hot update ${info.hotUpdateVersionCode})`,
  );
}

main();
